// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCokFGbpzoXLJ3wYgQ6MJvMfet8pSwzGFE',
    appId: '1:466795290087:android:877ff29f649e0763ee7142',
    messagingSenderId: '466795290087',
    projectId: 'backend-5da21',
    storageBucket: 'backend-5da21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_D7Gyp8Zkm7ewYQo0NfBTcXw3ZkQDmxk',
    appId: '1:466795290087:ios:2fc3edfce3bd8acbee7142',
    messagingSenderId: '466795290087',
    projectId: 'backend-5da21',
    storageBucket: 'backend-5da21.appspot.com',
    androidClientId:
        '466795290087-75bgr2ajpvda5frl89ko87q97pcjar3u.apps.googleusercontent.com',
    iosClientId:
        '466795290087-qsgu0jajoi9dga3jeokqcbuijqjis1gf.apps.googleusercontent.com',
    iosBundleId: 'com.example.isl',
  );
}
